apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgerock-ig
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: forgerock-ig
        image: forgerock/ig:latest
        env:
        - name: IG_CONFIG
          valueFrom:
            configMapKeyRef:
              name: ig-config
              key: ig.properties
